### PR TITLE
fix: exchange owner check fail

### LINKED ISSUE #2240: In the `ResumeExchange` and `SuspendExchange` instructions, the payer is validated against both `state.owner` and `foundation_allowlist`
This check will fail if the exchange owner is removed from the foundation_allowlist

### PR DESCRIPTION
**Pull request by ANISH-SR**
## Summary of Changes
* ResumeExchange / SuspendExchange: Updated authorization to allow the exchange owner or anyone in foundation_allowlist. 
* Owners can now resume/suspend even if they are not allowlisted.
* Fixed both processors to follow the same rule.
* Added unit tests for owner-allowed and non-owner-deny cases in both resume and suspend modules.
* Tests now construct Exchange explicitly instead of using default().

## Testing Verification
* rust checks green

fixes #2240

### CODE REVIEW

File: smartcontract/programs/doublezero-serviceability/src/processors/exchange/resume.rs [hunk 1]
```diff
@@ -59,16 +59,23 @@ pub fn process_resume_exchange(
...
-    }
 
+    // Parse accounts
+    let globalstate = globalstate_get(globalstate_account)?;
     let mut exchange: Exchange = Exchange::try_from(exchange_account)?;
 
-    if exchange.owner != *payer_account.key {
-        return Err(solana_program::program_error::ProgramError::Custom(0));
+    // Authorization:
+    //  - The exchange owner can always resume their own exchange, even if they
```
Comment (snormore) [inline smartcontract/programs/doublezero-serviceability/src/processors/exchange/resume.rs]: Can you remove the owner check? This should actually only be authorized by foundation list.

Comment (ANISH-SR) [reply smartcontract/programs/doublezero-serviceability/src/processors/exchange/resume.rs]: Done!

**Comment by ANISH-SR** [comment]
Hi @snormore , made the formatting changes in the latest commit. Can you please review this. Thanks!

**Review by karl-dz — CHANGES_REQUESTED** [review]
