### PR TITLE
Smartcontract: Add ResourceExtension and Foundation Commands for Managing

### LINKED ISSUE #2386: Phase 0: replace unwrap with proper error handling
In `processors/resource/allocate.rs:156`, `resource.allocate().unwrap()` will panic on-chain if allocation fails. Should return `ProgramError::Custom` with `BitmapFull` error code.

### LINKED ISSUE #2387: Phase 0: guard msg! calls behind cfg(test)
Several `msg!()` debug calls in `create_account.rs` and processors are not guarded by `#[cfg(test)]`. These consume compute units in production and should be behind cfg(test)

### LINKED ISSUE #2389: Phase 0: Support all three IP block types in SDK resource commands
SDK commands in `commands/resource/allocate.rs` and `deallocate.rs` are hardcoded to `IpBlockType::DeviceTunnelBlock`. Should accept parameter for DeviceTunnelBlock, UserTunnelBlock, or MulticastGroupBlock.

### LINKED ISSUE #2390: Phase 1: Implement `CreateResourceExtension` instruction
Add instruction to initialize ResourceExtension PDA accounts. Accept parameters for scope (global vs device), IP block configuration, ID bitmap configuration. Authorization: `foundation_allowlist` only.

### LINKED ISSUE #2392: Phase 1: Add `IdBitmap` type for TunnelId and SegmentRoutingId
Create `IdBitmap` struct for integer ID allocation. Fields: `id_type: IdType`, `start_offset: u16` (e.g., 500), `bitmap: [u64; 64]` (4096 slots), `allocated_count: u16`, `first_free_index: u32`. Used for per-device TunnelId (500-4095) and SegmentRoutingId.

### LINKED ISSUE #2393: Phase 1: Implement per-device ResourceExtension PDA derivation
Add `get_device_resource_extension_pda(program_id, device_pk)` using seeds `["resource_ext", device_pubkey]`. Contains TunnelId, SegmentRoutingId, and DzIp bitmaps.

### LINKED ISSUE #2394: Phase 1: Implement global ResourceExtension PDA derivation
Add `get_global_resource_extension_pda(program_id)` using seeds `["resource_ext", Pubkey::default()]`. Contains UserTunnelNet, LinkTunnelNet, and Multicast IP bitmaps.

### LINKED ISSUE #2395: Phase 1: Implement `ReleaseResource` instruction (manual slot release)
Add instruction (variant 84) to manually release a specific slot. Foundation escape hatch for edge cases. Accepts: resource_ext account, resource_type, slot index. Authorization: `foundation_allowlist` only.

### LINKED ISSUE #2396: Phase 1: Define error codes for resource allocation failures
Add to `DoubleZeroError` enum: `BitmapFull`, `ResourceExtensionNotFound`, `DeviceNotActivated`, `InvalidResourceType`, `SlotAlreadyAllocated`, `SlotNotAllocated`.

### LINKED ISSUE #2397: Phase 1: Add CLI commands for `CreateResourceExtension`
Add `doublezero resource create-extension` with options `--global` or `--device <pubkey>`. Include configuration for IP blocks and ID ranges.

### LINKED ISSUE #2399: Phase 1: Add SDK commands for `CreateResourceExtension`
Add `CreateResourceExtensionCommand` with builder pattern for scope, IP block parameters, ID bitmap parameters.

### PR DESCRIPTION
**Pull request by elitegreg**
## Summary of Changes
- Adds ResourceExtension to the smartcontract. This account tracks either IP or ID resources using a bitmap.
- Adds create/allocate/deallocate/get SDK methods for ResourceExtension
- Adds create/allocate/deallocate/get CLI commands for ResourceExtension (Foundation allowlist only)

## Testing Verification
- Added new unit tests
- Tested with a test solana instance manually from the command line

Closes #2386
Closes #2387
Closes #2389
Closes #2390
Closes #2392
Closes #2393
Closes #2394
Closes #2395
Closes #2396
Closes #2397
Closes #2399

### CODE REVIEW

File: smartcontract/programs/doublezero-serviceability/src/processors/resource/allocate.rs [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+
+#[derive(BorshSerialize, BorshDeserializeIncremental, PartialEq, Clone, Default)]
+pub struct ResourceAllocateArgs {
+    pub resource_type: crate::resource::ResourceType,
+    pub requested: Option<IdOrIp>,
+}
+
+impl fmt::Debug for ResourceAllocateArgs {
+    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
+        write!(f, "ResourceAllocateArgs {{}}",)
```
Comment (elitegreg) [inline smartcontract/programs/doublezero-serviceability/src/processors/resource/allocate.rs]: Add fields

File: smartcontract/programs/doublezero-serviceability/src/processors/resource/create.rs [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+use std::fmt;
+
+#[derive(BorshSerialize, BorshDeserializeIncremental, PartialEq, Clone, Default)]
+pub struct ResourceCreateArgs {
+    pub resource_type: crate::resource::ResourceType,
+}
+
+impl fmt::Debug for ResourceCreateArgs {
+    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
+        write!(f, "ResourceCreateArgs {{}}",)
```
Comment (elitegreg) [inline smartcontract/programs/doublezero-serviceability/src/processors/resource/create.rs]: Add fields

File: smartcontract/programs/doublezero-serviceability/src/processors/resource/create.rs [hunk 3]
```diff
@@ -0,0 +1,81 @@
...
+    );
+    // Check if the account is writable
+    assert!(resource_account.is_writable, "PDA Account is not writable");
+
+    let globalstate = globalstate_get(globalstate_account)?;
+    if !globalstate.foundation_allowlist.contains(payer_account.key) {
+        return Err(DoubleZeroError::NotAllowed.into());
+    }
+
+    super::create_resource(
```
[the remark this answers is not in the document]
Comment (elitegreg) [reply smartcontract/programs/doublezero-serviceability/src/processors/resource/create.rs]: It will be called from elsewhere in the near future
