### PR TITLE
smartcontract: fix multicast allowlist for allow_multiple_ip access passes

### LINKED ISSUE #3551: smartcontract: multicast allowlist fails for allow_multiple_ip access passes
## Summary

Calling `doublezero multicast group allowlist subscriber add` (or publisher) with a real client IP panics on-chain with `AccessPass client_ip does not match` when the AccessPass was created with `allow_multiple_ip=true`.

## Root cause

AccessPasses created with `allow_multiple_ip=true` store `client_ip = 0.0.0.0` and live at the dynamic PDA `(0.0.0.0, user_payer)`. The allowlist processors for both `AddMulticastGroupSubAllowlist` and `AddMulticastGroupPubAllowlist` (and their `Remove` counterparts) had two problems:

1. **PDA validation** only accepted the static PDA derived from `(value.client_ip, user_payer)`. When the AccessPass lives at `(0.0.0.0, user_payer)`, this derivation produces the wrong address and the assertion fails.
2. **client_ip equality check** compared the stored `accesspass.client_ip` (which is `0.0.0.0`) against `value.client_ip` (the real IP passed by the caller), always failing for `allow_multiple_ip` passes.

On the SDK side, `AddMulticastGroupSubAllowlistCommand` and the publisher equivalent were unconditionally deriving the static PDA from `(client_ip, user_payer)`, so they always sent the wrong account.

## Observed error

```
thread 'main' panicked at 'AccessPass client_ip does not match'
```

Triggered by:

```
doublezero multicast group allowlist subscriber add \
  --code mg03 \
  --client-ip 98.46.188.245 \
  --user-payer DZjZR4QB7woRRywaCab9hU5D8QHAtVnbGjFXtK9QFuam
```

```                                                                                         
  Program Logs:                                                                                                                                               
  Program DZtnuQ839pSaDMFG5q1ad2V95G82S5EC4RrB3Ndw2Heb invoke [1]                                                                                             
  Program log: Instruction: AddMulticastGroupSubAllowlist(client_ip: 98.46.188.245, user_payer: DZjZR4QB7woRRywaCab9hU5D8QHAtVnbGjFXtK9QFuam)                 
  Program log: panicked at smartcontract/programs/doublezero-serviceability/src/processors/multicastgroup/allowlist/subscriber/add.rs:141:9:                  
  AccessPass client_ip does not match                                                                                                                         
  Program DZtnuQ839pSaDMFG5q1ad2V95G82S5EC4RrB3Ndw2Heb consumed 8672 of 200000 compute units                                                                  
  Program DZtnuQ839pSaDMFG5q1ad2V95G82S5EC4RrB3Ndw2Heb failed: SBF program panicked                                                                           
  Error: Error processing Instruction 0: Program failed to complete
```

### PR DESCRIPTION
**Pull request by juan-malbeclabs**
Resolves: #3551

## Summary of Changes
- Fix `AddMulticastGroupSubAllowlist`, `RemoveMulticastGroupSubAllowlist`, `AddMulticastGroupPubAllowlist`, and `RemoveMulticastGroupPubAllowlist` to correctly handle AccessPasses created with `allow_multiple_ip=true`. These passes store `client_ip=0.0.0.0` and live at the dynamic PDA `(0.0.0.0, user_payer)`. The processors were doing a strict `client_ip` equality check that always failed when a real IP was passed in the instruction args.
- Add `resolve_accesspass_pda` to the SDK allowlist module. It tries the static PDA first and falls back to the dynamic PDA when an `allow_multiple_ip` pass is found there. Both `AddMulticastGroupSubAllowlistCommand` and `AddMulticastGroupPubAllowlistCommand` now use it.

## Diff Breakdown
| Category   | Files | Lines (+/-)   | Net   |
|------------|-------|---------------|-------|
| Core logic | 7     | +254 / -18    | +236  |
| Tests      | 3     | +868 / -0     | +868  |

Mostly tests; the core fix is a small but targeted change to 4 processor files and the SDK PDA resolution logic.

<details>
<summary>Key files (click to expand)</summary>

- `smartcontract/programs/doublezero-serviceability/tests/multicastgroup_allowlist_subcriber_test.rs` — 3 new integration tests for subscriber allowlist: `allow_multiple_ip` with zero IP in args, with real IP in args, and wrong PDA rejected
- `smartcontract/programs/doublezero-serviceability/tests/multicastgroup_allowlist_publisher_test.rs` — same 3 scenarios for publisher allowlist
- `smartcontract/sdk/rs/src/commands/multicastgroup/allowlist/mod.rs` — new `resolve_accesspass_pda` helper + 4 unit tests covering all PDA resolution branches
- `smartcontract/programs/doublezero-serviceability/src/processors/multicastgroup/allowlist/subscriber/add.rs` — PDA validation extended to accept dynamic PDA; `client_ip` check made conditional on `!allow_multiple_ip()`
- `smartcontract/programs/doublezero-serviceability/src/processors/multicastgroup/allowlist/publisher/add.rs` — same fix as subscriber add
- `smartcontract/programs/doublezero-serviceability/src/processors/multicastgroup/allowlist/subscriber/remove.rs` — same fix applied to remove path
- `smartcontract/programs/doublezero-serviceability/src/processors/multicastgroup/allowlist/publisher/remove.rs` — same fix applied to remove path

</details>

## Testing Verification
- 6 new program integration tests covering `allow_multiple_ip` add/remove (pub and sub) and wrong-PDA rejection
- 4 new SDK unit tests covering all branches of `resolve_accesspass_pda`
- All existing allowlist integration tests continue to pass

### CODE REVIEW

File: smartcontract/sdk/rs/src/commands/multicastgroup/allowlist/publisher/add.rs [hunk 1]
```diff
@@ -1,7 +1,9 @@
-use crate::{commands::multicastgroup::get::GetMulticastGroupCommand, DoubleZeroClient};
+use crate::{
```
Comment (martinsander00) [inline smartcontract/sdk/rs/src/commands/multicastgroup/allowlist/publisher/add.rs:1]: do we need to also wire in the remove.rs from publisher and subscriber in the sdk?

File: smartcontract/programs/doublezero-serviceability/tests/multicastgroup_allowlist_subcriber_test.rs [hunk 2]
```diff
@@ -762,6 +762,447 @@ async fn test_multicast_subscriber_allowlist_feed_authority_different_user_payer
     );
 }
 
+/// AccessPass with allow_multiple_ip=true (dynamic PDA at 0.0.0.0) can be added/removed from subscriber allowlist.
```
Comment (martinsander00) [inline smartcontract/programs/doublezero-serviceability/tests/multicastgroup_allowlist_subcriber_test.rs:765]: should we add a test combining `allow_multiple_ip=true + feed authority signing + value.user_payer ≠ accesspass.user_payer`?

File: smartcontract/sdk/rs/src/commands/multicastgroup/allowlist/publisher/add.rs (hunk 1 above)
Comment (juan-malbeclabs) [reply smartcontract/sdk/rs/src/commands/multicastgroup/allowlist/publisher/add.rs:1]: Fixed. Both publisher/remove.rs and subscriber/remove.rs now use resolve_accesspass_pda instead of get_accesspass_pda directly. Also found that the subscriber remove processor was missing the feed authority bypass that the add processor has — fixed that too for consistency.

File: smartcontract/programs/doublezero-serviceability/tests/multicastgroup_allowlist_subcriber_test.rs (hunk 2 above)
Comment (juan-malbeclabs) [reply smartcontract/programs/doublezero-serviceability/tests/multicastgroup_allowlist_subcriber_test.rs:765]: Added test_multicast_subscriber_allowlist_allow_multiple_ip_feed_authority_different_user_payer covering that combination for both add and remove. While adding it, found that the subscriber remove processor was missing the feed authority user_payer bypass that the add processor has — fixed that inconsistency too.

**Review by martinsander00 — APPROVED** [review]
